version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dating_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/dating_db

  bot:
    build: ./bot
    container_name: dating_bot
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/users/register
      - BOT_TOKEN=8700490908:AAH6RefsDsUcFXodueWOaotBjp8t-hl6_5s

  db:
    image: postgres:15
    container_name: dating_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dating_db
    ports:
      - "5433:5432"